### ISSUE TITLE
Scanning for titles fails when attempted

### ISSUE THREAD

**Issue by Masamune3210** [julesontheroad/NSC_BUILDER#144] opened 2020-07-08 02:34 UTC
When scanning for installed titles is attempted, the switch rapidly scrolls through the contents of the storage, including the sd card, and then stops after a bit. The script on the pc side outputs no data and instead spits out a Press Any key after a second with no other action

![image](https://user-images.githubusercontent.com/1053504/86868067-a2ad0a00-c099-11ea-862c-96a5ca7a6411.png)

**Comment by Masamune3210** [comment] 2020-07-08 02:35
The responder also has to be manually restarted after this, as it seems to get stuck on something and won't respond otherwise

**Comment by julesontheroad** [comment] 2020-07-08 08:09
I can add another config to limit the sd to certain folders i guess in case the problem is the connection dies before the process is completed. The sd is scanned searching for xci recursively, maybe the scan can get stucked for some reason. I can also disable the SD scans as an option and it will only show information for installables.
**I think these 2 are worth to add.**

When it works you see something like this:
![tabulate](https://user-images.githubusercontent.com/42461174/86894194-091a4280-c103-11ea-930b-4f9c019f1bd3.PNG)

**Comment by julesontheroad** [comment] 2020-07-08 08:13
When it works it should show something like this
![updates](https://user-images.githubusercontent.com/42461174/86894659-ab3a2a80-c103-11ea-8fcd-ef8753de142c.PNG)

**Comment by julesontheroad** [comment] 2020-07-08 10:30
What I realized is that the latest versions.txt is broken so that one won't show new updates. I can add the json as fallback since it's fine. I'll make that change later
https://github.com/blawar/titledb/blob/master/versions.txt
As you can see is missing the version numbers are missing so that part is detected as 0.
json is fine: https://github.com/blawar/titledb/blob/master/versions.json
The autoupdater works but that's because it takes your local libraries or google drive libraries as reference to get the new version numbers.

**Comment by julesontheroad** [comment] 2020-07-20 23:21
Leaving this one open since i didn't add the option to scan only installed games yet.

**Comment by julesontheroad** [comment] 2020-09-30 00:02
Closing this because xci games scans are now limited to folders set on **zconfig\mtp_xci_locations.txt** for beta and master branch which prevent scanning folders with a lot of files, like mod folders or emuiibo folders.
To scan all SD a user can remove the file.
Change is currently on beta and master branches.

**Closed by julesontheroad** 2020-09-30 00:02 UTC
