### ISSUE TITLE
error message during  repacking with 0.81

### ISSUE THREAD

**Issue by pipostyle** [julesontheroad/NSC_BUILDER#21] opened 2019-03-20 22:33 UTC
i had this issue while repacking on different xci

this issue happen with 0.81d version but not with 0.79. 

So packed xci is corrupted and doesn't work 

the message is "Checking meta:
        Updating cnmt hashes:
        - Calculated hash from pfs0:
Exception: local variable 'sha2' referenced before assignment
DONE

   /@
   \ \
 ___\ \
(__O)  \
(____@) \
(____@)  \
(__o)_    \
      \    \

HOPE YOU HAVE A FUN TIME "

**Comment by julesontheroad** [comment] 2019-03-21 01:33
Yeah i changed the building modes for 0.80 and then again for 0.81. 0.80-c can be considered the most stable version currently.
https://github.com/julesontheroad/NSC_BUILDER/releases/edit/v0.80-c

Either way if i'm right the error shows when patching the RSV for a xci file (game that had xci as origin) but not when patching a nsp file. The exception came from a print were it referenced **sha2** instead of **sha**
Should be fixed now in latest master for the beta branch:
https://github.com/julesontheroad/NSC_BUILDER/archive/Beta.zip

**Comment by julesontheroad** [comment] 2019-03-21 14:46
Seems like the exes didn't compile correctly for the last update in the master, the python version should be ok.
I'll recompile and check at night. (yesterday was late so I only checked the fix in python, but not that the exes were correct)

**Comment by pipostyle** [comment] 2019-03-21 18:21
yes i confirm, nothing work at all

can't chose an option without crash

**Comment by julesontheroad** [comment] 2019-03-22 00:35
Is fixed now. It seems the issue is on github's side. Apparently when you download the master as zip it messes the exes from squirrel, they work fine when doing a sync with github client but they don't work if you download the zip.
To solve it without doing a release I had to zip the x86 and x64 folders in the master. The python folder is unnafected since it's raw code apparently.
https://github.com/julesontheroad/NSC_BUILDER/archive/Beta.zip

**Comment by pipostyle** [comment] 2019-03-23 11:12
perfect, all is working

**Closed** 2019-04-15 05:35 UTC
