### ISSUE TITLE
custom files corruption due to file order detection

### ISSUE THREAD

**Issue by pcwizard7** [julesontheroad/NSC_BUILDER#132] opened 2020-06-07 15:45 UTC
custom xci are corrupted with nxdumptool @DarkMatterCore dumps due to file order detection

for more information go here
https://github.com/DarkMatterCore/nxdumptool/issues/59

**Comment by julesontheroad** [comment] 2020-06-09 13:57
I give you an answer in the other thread. I'll repeat it here. I think i already explain the issue as being related to tickets once, i have several approachs to prevent it but few time to start making dumps and debugging the issue currently. Also it would be interesting if you could test it with the beta, it includes my latest work and i've made several changes during the last months.

> The order doesn't matter headers are read and the order is decided by the cnmt to match Nintendo behavour.
I imagine the issue is on the tickets, probably some part of the function used uses my old code, more based on nut and more ticket dependant. The expected format of the ticket is scene format which was based on update tickets with the introduction of new flags in tickets nxdumptool tries to include it while the rest of the dumpers ignore them, i fixed it the first time it happened in the ticket library, my best guess is it happened again and is better to readapt all the functions to ignore tickets except for titlekeys.
I would have to look into the dump itself but i'm 100% sure is unrelated to file order specially since NSCB also uses the cnmt order. I don't know when i'll have time to check though i'm pretty busy with work.

**Comment by julesontheroad** [comment] 2020-06-09 18:08
I went and tested dumping the PC simulator game and update with nxdumptool and didn't find any issue with the dump of the game or update. I also answered in the nxdumptool thread but i would keep things here for further discussion.

> @DarkMatterCore @pcwizard7 I went and dump that same game and update with latest nxdumptool, in latest SX OS with FW 10.03 on the switch, using the same options. Then I did a verification with my tool, etc... and i didn't find issues. My first test test was with the beta and the second with the 0.98b exe from some months back.
I also tested the update in the text files. I actually didn't even find new flags in the tickets of either game or update so I don't really get what's the issue here but since pcwizard7 opened an issue in my git i would close this one, i can try to help him from there.
Also base was dumped splitted and joined back on the pc.
**Attached are the verification logs**.
[PC Building Simulator v131072 (010072800CBE8800) (UPD)-verify.txt](https://github.com/julesontheroad/NSC_BUILDER/files/4753970/PC.Building.Simulator.v131072.010072800CBE8800.UPD.-verify.txt)
[PC Building Simulator [010072800CBE8000] [v0]-verify.txt](https://github.com/julesontheroad/NSC_BUILDER/files/4753971/PC.Building.Simulator.010072800CBE8000.v0.-verify.txt)

**Comment by pcwizard7** [comment] 2020-06-10 06:49
thanks for reply yea we were stumped because we compare dumps made with nxdumptool and sxdumptool and compared them and couldn't find any differences except the nxdumptool dumps keep XMLs and JGP files which shouldn't make a difference  and file order (i might explain this wrong) in dump

and found it wired unpack and repack using hactool fix it

I ll be happy to test the beta and get back to you

thanks

**Comment by pcwizard7** [comment] 2020-06-10 06:54
I ll be testing the beta build for you and get back to you. I was using the last build you had on github 0.98b

**Comment by julesontheroad** [comment] 2020-06-10 08:57
It's only python for now https://github.com/julesontheroad/NSC_BUILDER/tree/Beta
The thing is i also tried wit 0.98b x64 and i didn't find issues. I also checked the tickets before and after installation and they were equal. I wonder what happened there. I also realized that keygeneration on your nut-info files was detected correctly in the ticket
Another thing you can try is replacing this info.bat file in ztools.  It won't solve the issue but i put pauses after every info function so you should be able to see the error the program gives you. We can continue from there
[info.zip](https://github.com/julesontheroad/NSC_BUILDER/files/4757271/info.zip)

**Comment by julesontheroad** [comment] 2020-06-11 11:02
The order is actually decided by the order in the text list. So basically if you only add files to make a xci it'll add them to the xci in the order you added them. If you added via a folder the order will be alphabetical due to the scanning of the folder.
If you added files for multiple xcis I think it scanned first the base files on the list though I would need to check. Order could be enforced easily too.
Anyway I still have to check making the xci, outputting info from it and testing the xci in the console. I'll report back.

**Comment by pcwizard7** [comment] 2020-06-11 11:08
so if i add the files one at a time base then update it may fix?

anyway I 'll wait until hear from you

**Comment by julesontheroad** [comment] 2020-06-13 10:46
I checked making the xci with the dumped files but i didn't have any issue loading the file in the information tool or in sx os.

**Comment by pcwizard7** [comment] 2020-06-13 12:09
did u use sxdumper or nxdumptool? sxdumper is fine. 
did u add the files to list one at a time or by folder?
I use the bat file to run the processes do u say do it manually? if so how?

could u upload a pre config copy of nsc or tell me what your process is?

**Comment by julesontheroad** [comment] 2020-06-14 01:45
i installed the dump i had with rommenu, then nxdumptool to dump, then i merged the fat32 parts and used my tool to make the xci dragging the folder. I used lastest nxdumptool and  sx os. Actually if in your case it works after rebuilding the nsps you could change to legacy mode, legacy extracts the ncas first and rebuilds the xci\nsp from that.
I think we all forgot (even myself) that legacy can be used when some issue arise in the main mode.

**Comment by pcwizard7** [comment] 2020-06-15 15:33
I ve tested two games so far that worked will do more tomorrow but i wanted to report something and get your answer on it

1. the way i got two games to work is add the two files to combine one at a time instead of via folder. in explorer, base file would appear first still then update file so the order should stay right?

2. does compressing  xci/nsp wipe the cert/titlekey ? because i looked into a file xci after it was decompressed and gamecardcert was zero out with (fffffffff) 

3. a game update has a "masterKeyRev =  0xb" does that mean theirs an 11 master key? lockpick_rcm doesn't seem to have a release update for it?

**Comment by julesontheroad** [comment] 2020-06-15 16:29
1.- The order doesn't really matter as far as i know, at least i never had issues due to order of files.
2.- Compressing stores the same ticket, the gamecart cert if you use a legit xci is wiped out since i generate one with the header i could add a check for legit cert but that would only be useful for online play. The ticket cert isn't wiped out unless you convert to standard crypto, the cert on an xci is different to a ticket one so it would get wiped out in coverssion anyway.
The titlekey isn't the same as the ticket when you convert the ncas to standard crypto, decrypted is still the same but is encrypted on ticket and is also encrypted according to the keygeneration.
3.- MasterkeyRev is the same as keygeneration so that's keygeneration 11. Basically it means MasterKeyRevision, that's inherited from nut.

**Comment by pcwizard7** [comment] 2020-06-25 05:05
Hi JROAD sorry for the late reply but i ve been redownloading all my again for fresh files and now start converting them. but 
drop-in to post infor

1. your latest changes in beta version has caused a bug in option 2 at least multi-content where it comes up error "low disk space required for output" even when there's enough space. but when i use older grab for nsc builder beta works fine

2. is it possible to get a bigger xci 32 GB files at all?

**Comment by julesontheroad** [comment] 2020-06-25 12:11
@pcwizard7 Should be fixed now the condition wasn't set up properly. 
2. Unfortunetly not till Nintendo start making 64GB xci and Xecuter adds whatever they need to change in the loader.

**Comment by pcwizard7** [comment] 2020-06-29 14:27
Update: so far tested 7 radium games and worked fine mounted and got to game title screen. I keep going

Let me know if u want to know the game titles as I do them?

**Comment by pcwizard7** [comment] 2020-06-30 02:41
I ve pulled the latest beta and game popup with an error when converting

Exception: list index out of range

FAST RMX [01009510001CA000][v0][BASE].nsp

***************
DECRYPTION TEST
***************
01009510001CA000 - Content.PROGRAM
        28ca27165c6036d64a03f00a563ee141.nca      -> is CORRECT
01009510001CA000 - Content.CONTROL
        7c59e3f5f36be5ba2771fd4dfc6877e1.nca      -> is CORRECT
01009510001CA000 - Content.MANUAL
        0d5dd3ab358cda5785bb266214beb5b0.nca      -> is CORRECT
01009510001CA000 - Content.META
        4efa1839e344ea3e896cf0a7c45af713.cnmt.nca -> is CORRECT
Content.TICKET
        01009510001ca0000000000000000000.tik      -> is CORRECT

VERDICT: NSP FILE IS CORRECT

****************
SIGNATURE 1 TEST
****************
01009510001CA000 - Content.PROGRAM
    > 28ca27165c6036d64a03f00a563ee141.nca        -> is PROPER

01009510001CA000 - Content.CONTROL
    > 7c59e3f5f36be5ba2771fd4dfc6877e1.nca        -> is PROPER

01009510001CA000 - Content.MANUAL
    > 0d5dd3ab358cda5785bb266214beb5b0.nca        -> is PROPER

01009510001CA000 - Content.META
    > 4efa1839e344ea3e896cf0a7c45af713.cnmt.nca   -> is PROPER

VERDICT: NSP  FILE IS SAFE

***************
HASH TEST
***************
01009510001CA000 - Content.PROGRAM
  - File name: 28ca27165c6036d64a03f00a563ee141.nca
  - SHA256: 28ca27165c6036d64a03f00a563ee141dfaff99dcf91af2b33722ba4e54f6800
   > FILE IS CORRECT

01009510001CA000 - Content.CONTROL
  - File name: 7c59e3f5f36be5ba2771fd4dfc6877e1.nca
  - SHA256: 7c59e3f5f36be5ba2771fd4dfc6877e15b9f44a71c959be2a6def279a087221a
   > FILE IS CORRECT

01009510001CA000 - Content.MANUAL
  - File name: 0d5dd3ab358cda5785bb266214beb5b0.nca
  - SHA256: 0d5dd3ab358cda5785bb266214beb5b0ccecc9c49fe912b9287cf1077b9e46df
   > FILE IS CORRECT

01009510001CA000 - Content.META
  - File name: 4efa1839e344ea3e896cf0a7c45af713.cnmt.nca
  - SHA256: 4efa1839e344ea3e896cf0a7c45af713588de3a71e504107437196b6b27db6b5
   > FILE IS CORRECT

VERDICT: NSP FILE IS CORRECT

FAST RMX [01009510001CA800][v196608][UPD].nsp

********************************************************
VERIFY A NSP\XCI\NCA
********************************************************
***************
DECRYPTION TEST
***************
01009510001CA000 - Content.PROGRAM
        02d1b5ab1984c6c7d1e1f98a9f065b4e.nca      -> is CORRECT
01009510001CA000 - Content.CONTROL
        894ba680010fe93e37da1f38f4629d3a.nca      -> is CORRECT
01009510001CA000 - Content.MANUAL
        ccf23fc3950b2b37a6a849d6e162f484.nca      -> is CORRECT
01009510001CA800 - Content.META
        45521e8dea684a52bd0f3e3f5f45c88c.cnmt.nca -> is CORRECT
Content.TICKET
        01009510001ca8000000000000000000.tik      -> is CORRECT

VERDICT: NSP FILE IS CORRECT

****************
SIGNATURE 1 TEST
****************
01009510001CA000 - Content.PROGRAM
    > 02d1b5ab1984c6c7d1e1f98a9f065b4e.nca        -> is PROPER

01009510001CA000 - Content.CONTROL
    > 894ba680010fe93e37da1f38f4629d3a.nca        -> is PROPER

01009510001CA000 - Content.MANUAL
    > ccf23fc3950b2b37a6a849d6e162f484.nca        -> is PROPER

01009510001CA800 - Content.META
    > 45521e8dea684a52bd0f3e3f5f45c88c.cnmt.nca   -> is PROPER

VERDICT: NSP  FILE IS SAFE

***************
HASH TEST
***************
01009510001CA000 - Content.PROGRAM
  - File name: 02d1b5ab1984c6c7d1e1f98a9f065b4e.nca
  - SHA256: 02d1b5ab1984c6c7d1e1f98a9f065b4e630f38bf85249db955df8928363b102e
   > FILE IS CORRECT

01009510001CA000 - Content.CONTROL
  - File name: 894ba680010fe93e37da1f38f4629d3a.nca
  - SHA256: 894ba680010fe93e37da1f38f4629d3a8217aed2c8c54a6cb690f389471b3155
   > FILE IS CORRECT

01009510001CA000 - Content.MANUAL
  - File name: ccf23fc3950b2b37a6a849d6e162f484.nca
  - SHA256: ccf23fc3950b2b37a6a849d6e162f4843dd34ce12649989abe7e5a4a5919a748
   > FILE IS CORRECT

01009510001CA800 - Content.META
  - File name: 45521e8dea684a52bd0f3e3f5f45c88c.cnmt.nca
  - SHA256: 45521e8dea684a52bd0f3e3f5f45c88c0fbc816ad8acdd06f9438f86cc5a7048
   > FILE IS CORRECT

VERDICT: NSP FILE IS CORRECT

**Comment by pcwizard7** [comment] 2020-06-30 03:34
another one 

I am Setsuna. [0100849000BDA000][v0][BASE]

********************************************************
VERIFY A NSP\XCI\NCA
********************************************************
***************
DECRYPTION TEST
***************
0100849000BDA000 - Content.PROGRAM
        c5d4a56bf5be6e29f4f778933797edba.nca      -> is CORRECT
0100849000BDA000 - Content.MANUAL
        cfabf482c64649183f94c5d6e81c43be.nca      -> is CORRECT
0100849000BDA000 - Content.CONTROL
        487c4c4b19e8adc8c054cd32e0c23a1e.nca      -> is CORRECT
0100849000BDA000 - Content.META
        972aaaf37c4e656cf03657320d256d31.cnmt.nca -> is CORRECT
Content.TICKET
        0100849000bda0000000000000000000.tik      -> is CORRECT

VERDICT: NSP FILE IS CORRECT

****************
SIGNATURE 1 TEST
****************
0100849000BDA000 - Content.PROGRAM
    > c5d4a56bf5be6e29f4f778933797edba.nca        -> is PROPER

0100849000BDA000 - Content.MANUAL
    > cfabf482c64649183f94c5d6e81c43be.nca        -> is PROPER

0100849000BDA000 - Content.CONTROL
    > 487c4c4b19e8adc8c054cd32e0c23a1e.nca        -> is PROPER

0100849000BDA000 - Content.META
    > 972aaaf37c4e656cf03657320d256d31.cnmt.nca   -> is PROPER

VERDICT: NSP  FILE IS SAFE

***************
HASH TEST
***************
0100849000BDA000 - Content.PROGRAM
  - File name: c5d4a56bf5be6e29f4f778933797edba.nca
  - SHA256: c5d4a56bf5be6e29f4f778933797edba311c6c2ffc7aac7151298103d5caf941
   > FILE IS CORRECT

0100849000BDA000 - Content.MANUAL
  - File name: cfabf482c64649183f94c5d6e81c43be.nca
  - SHA256: cfabf482c64649183f94c5d6e81c43bebd93e9959a0e20ef9bfee432ba8c88a9
   > FILE IS CORRECT

0100849000BDA000 - Content.CONTROL
  - File name: 487c4c4b19e8adc8c054cd32e0c23a1e.nca
  - SHA256: 487c4c4b19e8adc8c054cd32e0c23a1e01ccf061225816782864f3b623546d2f
   > FILE IS CORRECT

0100849000BDA000 - Content.META
  - File name: 972aaaf37c4e656cf03657320d256d31.cnmt.nca
  - SHA256: 972aaaf37c4e656cf03657320d256d31b0ddb312eb57ee05779b8ee809d3e74e
   > FILE IS CORRECT

VERDICT: NSP FILE IS CORRECT

I am Setsuna. [0100849000BDA800][v65536][UPD]

********************************************************
VERIFY A NSP\XCI\NCA
********************************************************
***************
DECRYPTION TEST
***************
0100849000BDA000 - Content.PROGRAM
        b0d3907285349e22b04bb6e3ee2d7136.nca      -> is CORRECT
0100849000BDA000 - Content.CONTROL
        31d9c8ca62e1c2d765d1a1e767aae1aa.nca      -> is CORRECT
0100849000BDA000 - Content.MANUAL
        e3f785ccc8474d54e26d4e526992ec0e.nca      -> is CORRECT
0100849000BDA800 - Content.META
        23f02f8e2e84d002010b5d4e14222e7d.cnmt.nca -> is CORRECT
Content.TICKET
        0100849000bda8000000000000000000.tik      -> is CORRECT

VERDICT: NSP FILE IS CORRECT

****************
SIGNATURE 1 TEST
****************
0100849000BDA000 - Content.PROGRAM
    > b0d3907285349e22b04bb6e3ee2d7136.nca        -> is PROPER

0100849000BDA000 - Content.CONTROL
    > 31d9c8ca62e1c2d765d1a1e767aae1aa.nca        -> is PROPER

0100849000BDA000 - Content.MANUAL
    > e3f785ccc8474d54e26d4e526992ec0e.nca        -> is PROPER

0100849000BDA800 - Content.META
    > 23f02f8e2e84d002010b5d4e14222e7d.cnmt.nca   -> is PROPER

VERDICT: NSP  FILE IS SAFE

***************
HASH TEST
***************
0100849000BDA000 - Content.PROGRAM
  - File name: b0d3907285349e22b04bb6e3ee2d7136.nca
  - SHA256: b0d3907285349e22b04bb6e3ee2d71364439a649efda3cc2fadd92e503791a5a
   > FILE IS CORRECT

0100849000BDA000 - Content.CONTROL
  - File name: 31d9c8ca62e1c2d765d1a1e767aae1aa.nca
  - SHA256: 31d9c8ca62e1c2d765d1a1e767aae1aa9f28a5519d1cdcf828ccdb67b63876ee
   > FILE IS CORRECT

0100849000BDA000 - Content.MANUAL
  - File name: e3f785ccc8474d54e26d4e526992ec0e.nca
  - SHA256: e3f785ccc8474d54e26d4e526992ec0ee3d32e3c5bd2b61b7bd936c75c3998df
   > FILE IS CORRECT

0100849000BDA800 - Content.META
  - File name: 23f02f8e2e84d002010b5d4e14222e7d.cnmt.nca
  - SHA256: 23f02f8e2e84d002010b5d4e14222e7de5bd199539bb943c90acc5d15313617a
   > FILE IS CORRECT

VERDICT: NSP FILE IS CORRECT

**Comment by pcwizard7** [comment] 2020-06-30 03:42
another one

IMPLOSION [0100737003190000][v0][BASE].nsp

********************************************************
VERIFY A NSP\XCI\NCA
********************************************************
***************
DECRYPTION TEST
***************
0100737003190000 - Content.PROGRAM
        44f21458bfd9d1238fe3e83ba78a7ff3.nca      -> is CORRECT
0100737003190000 - Content.CONTROL
        78c6dedbae7bc9521a57e54d73cb27f1.nca      -> is CORRECT
0100737003190000 - Content.MANUAL
        1d4ec7af54ab972dae1c3d420916c809.nca      -> is CORRECT
0100737003190000 - Content.META
        6e58afde3d132e327d3cf6497d9c02c7.cnmt.nca -> is CORRECT
Content.TICKET
        01007370031900000000000000000000.tik      -> is CORRECT

VERDICT: NSP FILE IS CORRECT

****************
SIGNATURE 1 TEST
****************
0100737003190000 - Content.PROGRAM
    > 44f21458bfd9d1238fe3e83ba78a7ff3.nca        -> is PROPER

0100737003190000 - Content.CONTROL
    > 78c6dedbae7bc9521a57e54d73cb27f1.nca        -> is PROPER

0100737003190000 - Content.MANUAL
    > 1d4ec7af54ab972dae1c3d420916c809.nca        -> is PROPER

0100737003190000 - Content.META
    > 6e58afde3d132e327d3cf6497d9c02c7.cnmt.nca   -> is PROPER

VERDICT: NSP  FILE IS SAFE

***************
HASH TEST
***************
0100737003190000 - Content.PROGRAM
  - File name: 44f21458bfd9d1238fe3e83ba78a7ff3.nca
  - SHA256: 44f21458bfd9d1238fe3e83ba78a7ff39dce5483f818f33ff5ff6f79c0b26eea
   > FILE IS CORRECT

0100737003190000 - Content.CONTROL
  - File name: 78c6dedbae7bc9521a57e54d73cb27f1.nca
  - SHA256: 78c6dedbae7bc9521a57e54d73cb27f1952735e5d7d409502c1de30e4f7565d1
   > FILE IS CORRECT

0100737003190000 - Content.MANUAL
  - File name: 1d4ec7af54ab972dae1c3d420916c809.nca
  - SHA256: 1d4ec7af54ab972dae1c3d420916c809fd2c1abba03cce28127b2f83d03e5627
   > FILE IS CORRECT

0100737003190000 - Content.META
  - File name: 6e58afde3d132e327d3cf6497d9c02c7.cnmt.nca
  - SHA256: 6e58afde3d132e327d3cf6497d9c02c758c1a60d198fe46846fd11e9d1a41eb9
   > FILE IS CORRECT

VERDICT: NSP FILE IS CORRECT

IMPLOSION [0100737003190800][v65536][UPD].nsp

********************************************************
VERIFY A NSP\XCI\NCA
********************************************************
***************
DECRYPTION TEST
***************
0100737003190000 - Content.PROGRAM
        1544366c4bfd16a810d27e07cb57eff6.nca      -> is CORRECT
0100737003190000 - Content.CONTROL
        85ffc8008f6e11c57a072c319b2dc24a.nca      -> is CORRECT
0100737003190000 - Content.MANUAL
        7c7a25e69e4c12915eb0bb24b4b1d47b.nca      -> is CORRECT
0100737003190800 - Content.META
        aa8060771d20a2ec8958589bd2763f8e.cnmt.nca -> is CORRECT
Content.TICKET
        01007370031908000000000000000003.tik      -> is CORRECT

VERDICT: NSP FILE IS CORRECT

****************
SIGNATURE 1 TEST
****************
0100737003190000 - Content.PROGRAM
    > 1544366c4bfd16a810d27e07cb57eff6.nca        -> is PROPER

0100737003190000 - Content.CONTROL
    > 85ffc8008f6e11c57a072c319b2dc24a.nca        -> is PROPER

0100737003190000 - Content.MANUAL
    > 7c7a25e69e4c12915eb0bb24b4b1d47b.nca        -> is PROPER

0100737003190800 - Content.META
    > aa8060771d20a2ec8958589bd2763f8e.cnmt.nca   -> is PROPER

VERDICT: NSP  FILE IS SAFE

***************
HASH TEST
***************
0100737003190000 - Content.PROGRAM
  - File name: 1544366c4bfd16a810d27e07cb57eff6.nca
  - SHA256: 1544366c4bfd16a810d27e07cb57eff6d238a426de69085129ebe79ba23cb27b
   > FILE IS CORRECT

0100737003190000 - Content.CONTROL
  - File name: 85ffc8008f6e11c57a072c319b2dc24a.nca
  - SHA256: 85ffc8008f6e11c57a072c319b2dc24a6fc4cf42f10a3ef85bc464985bd0978e
   > FILE IS CORRECT

0100737003190000 - Content.MANUAL
  - File name: 7c7a25e69e4c12915eb0bb24b4b1d47b.nca
  - SHA256: 7c7a25e69e4c12915eb0bb24b4b1d47b87c013d4c4871a65902f8ec3465b5126
   > FILE IS CORRECT

0100737003190800 - Content.META
  - File name: aa8060771d20a2ec8958589bd2763f8e.cnmt.nca
  - SHA256: aa8060771d20a2ec8958589bd2763f8e4e7e850672847a8a48459ba197b8389d
   > FILE IS CORRECT

VERDICT: NSP FILE IS CORRECT

**Comment by julesontheroad** [comment] 2020-06-30 09:56
Hmm those are keygeneration 1 so they should be using masterkey_0 to decrypt. I will check with those since it seems the common factor maybe i changed something somewhere that causes the issue.

**Comment by julesontheroad** [comment] 2020-06-30 11:01
I merged beta to master and issue a fix https://github.com/julesontheroad/NSC_BUILDER/commit/3fcd12de7cc0f6465d0f76ffec7cead70bc95142
I didn't update the beta directly since I had changes not uploaded meant to be a surprice for later this week.

Pretty sure the condition for that bug is having data in 0x144 of the ticket that gets mistaken as the keygeneration since i'm supporting 0x144 and 0x155 offsets. Anyway the current fix should avoid that, the verification works on those cases since it verifies the titlekey against ncas in a different way with the titlekey verification function that tests keys directly.

**Comment by pcwizard7** [comment] 2020-06-30 11:20
@julesontheroad 

1. so what does that mean and how do i apply/get the fix or do i wait for next update?

2. I ve got a byte view of the tik files in each nsp file here 
there's cert files too but not sure to include them too?

[upload.zip](https://github.com/julesontheroad/NSC_BUILDER/files/4851406/upload.zip)

**Comment by julesontheroad** [comment] 2020-06-30 12:07
@pcwizard7 I think the issue is the 20 in 0x286. Anyway, let me check changing my tickets to match yours since in theory the program doesn't look at that offset.

**Comment by julesontheroad** [comment] 2020-06-30 12:15
Ok, that's 20 there is the issue, i'll check what it's happening there and fix it:
![issue](https://user-images.githubusercontent.com/42461174/86124891-1cfaee80-badc-11ea-8cc1-93bcf4b22f9b.PNG)

**Comment by julesontheroad** [comment] 2020-06-30 12:53
Ok, now it's fixed. It was 0x145 since it was counting after the issuer. Normally the keygeneration should be in 0x144|0x285 depending from wgere you count but some legacy dumps have it on 0x145|0x286 so I try to support both offsets, the current fix should be enough to not drop support on that.

If you want the fix basically the current master is equal to the beta + that fix. I'll update the beta in a few days but currently i have some local commits for a new feature i don't want to reveal yet and adding that commit manually may mess with the beta tree on my experience.
Alternatively replace the Ticket class in FS/Ticket.
[Ticket.zip](https://github.com/julesontheroad/NSC_BUILDER/files/4851922/Ticket.zip)

**Comment by pcwizard7** [comment] 2020-07-01 16:00
Total 72 eshop games tested. just leftover and gamecart games to go and i would have redone my collection.

the three games with a low masterkeyrev worked the fix you gave me i guess you choose to make ignore and process it. you put more permant fix later i guess so it can support new and legacy titles as well?

thanks

**Comment by julesontheroad** [comment] 2020-07-02 00:17
The current one should be permanent ybh, the one from yesterday had a bug with the keygens that start using letters but i fixed it today. I realized it when i processed one file with kg 0b. The fix should affect legacy and new. Still i may add an aditional check when a keygeneration mismatch is detected so it doesn't exit.

**Comment by pcwizard7** [comment] 2020-07-02 18:40
> 2.- Compressing stores the same ticket, the gamecart cert if you use a legit xci is wiped out since i generate one with the header i could add a check for legit cert but that would only be useful for online play. The ticket cert isn't wiped out unless you convert to standard crypto, the cert on an xci is different to a ticket one so it would get wiped out in coverssion anyway.

I m done with eshop titles now gamecard games.
now back to other issue above i ve taken screenshots to show what i mean

this shows the original dump of a xci gamecart and i ve shown the first line of its cert
![xci uncompress file](https://user-images.githubusercontent.com/28586567/86397118-936b3c80-bce6-11ea-8661-7f96769d2738.jpg)

this shows the gamecart cert of same title from a xci that was made from a decompress xcz file
![xcz decompressed file](https://user-images.githubusercontent.com/28586567/86397231-cad9e900-bce6-11ea-9e08-36e6e9d031e6.jpg)

now with nsp files when you compress them they remove all jpg and xml files which makes them look less original than one made from Nintendo 

this shows the original dump of nsp eshop
![nsp uncompress file](https://user-images.githubusercontent.com/28586567/86397404-17bdbf80-bce7-11ea-9ed1-64e7a11ae538.jpg)

this shows the nsp files of the same title from a nsp  that was made from a decompress file
![nsx decompressed file](https://user-images.githubusercontent.com/28586567/86397485-420f7d00-bce7-11ea-80fd-e55354760125.jpg)

**Comment by julesontheroad** [comment] 2020-07-03 16:10
@pcwizard7 **Both things are intentional**, the xci header is regenerated in a shortened state and xci cert blanking is enforced. Would only serve to play online or get your card cert banned and i don't really see the boint. I could add an option but whatever.
Real nsps don't have jpgs and i think they don't really have xmls but would need to check. Those are sdk formats meant so you can read data without keys on pcs in my opinion, not really meant for delivery.
Some nsps meant for delivery can be found inside kiosk cartridges. These nsps as weird as it sounds are inside the program nca of the cartridge, when the cartridge is introduced it issues an auto installation of the nsps inside the program nca. 
**Anyway if you really want those things open a new issue, i think for nsps there are options to include all the files in the code but they may be enforced to exclude them. I only make the cnmt.xml because it may be useful to have what type is each nca in plaintext.**

**Comment by pcwizard7** [comment] 2020-07-03 17:42
1. I d only want cert in case i wanted online play, I thought as long as your the only one using it and they don't see multiple people using it

2. @DarkMatterCore had said the original nsp made for/by Nintendo include the extra jpg xml files. but yeah check

3. yea there no need for fw update in every game could save 200-300 mbs per game

**Comment by julesontheroad** [comment] 2020-07-03 23:24
1. It isn't really documented enough since few people tested it and they tend to get banned in time. Still I was told there were changes in auth for xci in 9.1 I think. Well i can add an option to keep it, though i can only tell you it won't be in next release.
2. The sdk includes it, yep. Anyway I'll think about the xmls and jpgs, i'm particularly not a fan of them and i designed everything with the intention of stripping them tbh.

**Comment by julesontheroad** [comment] 2020-07-06 22:58
Closing this @pcwizard7 If you want the last stuff you mentioned please open other issue since it's unrelated to this.

**Closed by julesontheroad** 2020-07-06 22:58 UTC
