### ISSUE TITLE
Interface.bat and Chromium

### ISSUE THREAD

**Issue by deejay87** [julesontheroad/NSC_BUILDER#168] opened 2020-07-17 17:15 UTC
Hi
What changes on 0.99 to use interface.bat ? 
I use this with Chromium on 0.98b en working perfectly, but can't do this working with the 0.99
Thanks

**Comment by julesontheroad** [comment] 2020-07-17 23:17
I did some fixes on the autoselection on the master and beta, when i forked eel to modify it and allow launching it without console and also as a remote server i forgot to rename some calls so python 0.99 works fine if you also have eel but some of the modes for browser launching are broken because of that bug in the exe.
So there are 3 approaches:
- Change the launching mode in the config to default so it uses your system browser.
- Use the python version from the master
- Wait for 1.0.0 on sunday or monday.
The bug is this one https://github.com/julesontheroad/NSC_BUILDER/commit/5ec69be005783274cb2ea495b3b684e1e307f1c8

As you can see the issue is i was using **import eel.browsers** there instead of **import _EEL_.browsers** which is the name i gave the fork to avoid issues if eel is also installed. I also use chromium but i didn't notice probably since i use the python version and also have eel installed.

Anyway if you can wait a few days it'll be fixed on the exe versions, or you can move to the python master or beta if you're in a hurry.
https://github.com/julesontheroad/NSC_BUILDER/archive/master.zip
https://github.com/julesontheroad/NSC_BUILDER/archive/Beta.zip

**Comment by deejay87** [comment] 2020-07-18 08:34
Thanks for the explanation, i do somes tests and have seen this only :)

**Comment by julesontheroad** [comment] 2020-07-20 23:18
This should be fixed here, waiting a couple of days for confirmation before closing.

**Closed** 2020-07-23 07:59 UTC
